# Generated by Django 4.2.1 on 2023-05-26 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0004_reviews"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
    ]
